package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"time"

	"codeberg.org/aros/dpview/internal/api"
	"codeberg.org/aros/dpview/internal/files"
)

type enumSpec struct {
	TypeName string
	Schema   string
	Values   []string
}

type generator struct {
	types     map[reflect.Type]string
	order     []reflect.Type
	enumNames map[reflect.Type]enumSpec
}

func main() {
	g := newGenerator()
	g.registerRoots(
		reflect.TypeOf(api.Error{}),
		reflect.TypeOf(api.FrontMatterEntry{}),
		reflect.TypeOf(api.FrontMatter{}),
		reflect.TypeOf(files.FileInfo{}),
		reflect.TypeOf(files.TreeNode{}),
		reflect.TypeOf(api.Preview{}),
		reflect.TypeOf(api.CurrentData{}),
		reflect.TypeOf(api.SeekData{}),
		reflect.TypeOf(api.FilesData{}),
		reflect.TypeOf(api.Settings{}),
		reflect.TypeOf(api.SettingsData{}),
		reflect.TypeOf(api.LogEntry{}),
		reflect.TypeOf(api.LogData{}),
		reflect.TypeOf(api.RendererStatus{}),
		reflect.TypeOf(api.Limits{}),
		reflect.TypeOf(api.WatcherStatus{}),
		reflect.TypeOf(api.HealthData{}),
	)

	output, err := g.render()
	if err != nil {
		fail(err)
	}

	root, err := findModuleRoot()
	if err != nil {
		fail(err)
	}
	target := filepath.Join(root, "cmd", "dpview", "web", "generated", "contracts.ts")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		fail(err)
	}
	if err := os.WriteFile(target, output, 0o644); err != nil {
		fail(err)
	}
}

func newGenerator() *generator {
	g := &generator{
		types: make(map[reflect.Type]string),
		enumNames: map[reflect.Type]enumSpec{
			reflect.TypeOf(files.Kind("")): {
				TypeName: "FileKind",
				Schema:   "fileKindSchema",
				Values:   []string{"markdown", "typst"},
			},
			reflect.TypeOf(api.RenderStatus("")): {
				TypeName: "RenderStatus",
				Schema:   "renderStatusSchema",
				Values:   []string{"idle", "rendering", "ready", "error"},
			},
		},
	}
	return g
}

func (g *generator) registerRoots(types ...reflect.Type) {
	for _, t := range types {
		g.register(t)
	}
}

func (g *generator) register(t reflect.Type) {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t == reflect.TypeOf(time.Time{}) {
		return
	}
	if _, ok := g.enumNames[t]; ok {
		return
	}
	if _, ok := g.types[t]; ok {
		return
	}
	if t.Kind() != reflect.Struct {
		return
	}

	name := typeName(t)
	g.types[t] = name
	g.order = append(g.order, t)

	for i := range t.NumField() {
		field := t.Field(i)
		if !field.IsExported() {
			continue
		}
		fieldType := field.Type
		for fieldType.Kind() == reflect.Pointer {
			fieldType = fieldType.Elem()
		}
		switch fieldType.Kind() {
		case reflect.Struct:
			if fieldType != reflect.TypeOf(time.Time{}) {
				g.register(fieldType)
			}
		case reflect.Slice:
			elem := fieldType.Elem()
			for elem.Kind() == reflect.Pointer {
				elem = elem.Elem()
			}
			if elem.Kind() == reflect.Struct && elem != reflect.TypeOf(time.Time{}) {
				g.register(elem)
			}
		}
	}
}

func (g *generator) render() ([]byte, error) {
	var out bytes.Buffer
	out.WriteString("// Code generated by go run ./cmd/gen-web-contracts. DO NOT EDIT.\n")
	out.WriteString("import { z } from \"zod\";\n\n")

	enumTypes := make([]reflect.Type, 0, len(g.enumNames))
	for t := range g.enumNames {
		enumTypes = append(enumTypes, t)
	}
	sort.Slice(enumTypes, func(i, j int) bool {
		return g.enumNames[enumTypes[i]].TypeName < g.enumNames[enumTypes[j]].TypeName
	})
	for _, t := range enumTypes {
		enum := g.enumNames[t]
		fmt.Fprintf(&out, "export const %sValues = [%s] as const;\n", lowerFirst(enum.TypeName), quoteJoin(enum.Values))
		fmt.Fprintf(&out, "export type %s = (typeof %sValues)[number];\n", enum.TypeName, lowerFirst(enum.TypeName))
		fmt.Fprintf(&out, "export const %s = z.enum(%sValues);\n\n", enum.Schema, lowerFirst(enum.TypeName))
	}

	for _, t := range g.order {
		fmt.Fprintf(&out, "export interface %s {\n", g.types[t])
		for i := range t.NumField() {
			field := t.Field(i)
			if !field.IsExported() {
				continue
			}
			jsonName, optional := jsonField(field)
			if jsonName == "-" {
				continue
			}
			fmt.Fprintf(&out, "    %s%s: %s;\n", jsonName, ternary(optional, "?", ""), g.tsType(field.Type))
		}
		out.WriteString("}\n\n")
	}

	for _, t := range g.order {
		schemaName := schemaName(g.types[t])
		fmt.Fprintf(&out, "export const %s: z.ZodType<%s> = %s;\n\n", schemaName, g.types[t], g.structSchema(t, t, false))
	}

	return out.Bytes(), nil
}

func (g *generator) tsType(t reflect.Type) string {
	optional := false
	for t.Kind() == reflect.Pointer {
		optional = true
		t = t.Elem()
	}
	var result string
	switch {
	case t == reflect.TypeOf(time.Time{}):
		result = "string"
	case g.enumNames[t].TypeName != "":
		result = g.enumNames[t].TypeName
	case g.types[t] != "":
		result = g.types[t]
	case t.Kind() == reflect.String:
		result = "string"
	case isIntKind(t.Kind()):
		result = "number"
	case isFloatKind(t.Kind()):
		result = "number"
	case t.Kind() == reflect.Bool:
		result = "boolean"
	case t.Kind() == reflect.Slice:
		result = g.tsType(t.Elem()) + "[]"
	case t.Kind() == reflect.Map:
		result = fmt.Sprintf("Record<string, %s>", g.tsType(t.Elem()))
	default:
		result = "unknown"
	}
	if optional {
		return result
	}
	return result
}

func (g *generator) schemaExpr(t reflect.Type, owner reflect.Type, passthrough bool) string {
	for t.Kind() == reflect.Pointer {
		return g.schemaExpr(t.Elem(), owner, passthrough) + ".optional()"
	}
	switch {
	case t == reflect.TypeOf(time.Time{}):
		return "z.string()"
	case g.enumNames[t].Schema != "":
		return g.enumNames[t].Schema
	case g.types[t] != "":
		return "z.lazy(() => " + schemaName(g.types[t]) + ")"
	case t.Kind() == reflect.String:
		return "z.string()"
	case isIntKind(t.Kind()):
		return "z.number().int()"
	case isFloatKind(t.Kind()):
		return "z.number()"
	case t.Kind() == reflect.Bool:
		return "z.boolean()"
	case t.Kind() == reflect.Slice:
		return "z.array(" + g.schemaExpr(t.Elem(), owner, true) + ")"
	case t.Kind() == reflect.Map:
		return "z.record(z.string(), " + g.schemaExpr(t.Elem(), owner, true) + ")"
	default:
		return "z.unknown()"
	}
}

func (g *generator) structSchema(t reflect.Type, owner reflect.Type, passthrough bool) string {
	var out bytes.Buffer
	if passthrough {
		out.WriteString("z.looseObject({\n")
	} else {
		out.WriteString("z.strictObject({\n")
	}
	for i := range t.NumField() {
		field := t.Field(i)
		if !field.IsExported() {
			continue
		}
		jsonName, optional := jsonField(field)
		if jsonName == "-" {
			continue
		}
		fmt.Fprintf(&out, "    %s: %s", jsonName, g.schemaExpr(field.Type, owner, true))
		if optional && field.Type.Kind() != reflect.Pointer {
			out.WriteString(".optional()")
		}
		out.WriteString(",\n")
	}
	out.WriteString("})")
	return out.String()
}

func typeName(t reflect.Type) string {
	switch t {
	case reflect.TypeOf(api.Error{}):
		return "ApiError"
	default:
		return t.Name()
	}
}

func schemaName(typeName string) string {
	return lowerFirst(typeName) + "Schema"
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	return strings.ToLower(value[:1]) + value[1:]
}

func quoteJoin(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return strings.Join(quoted, ", ")
}

func jsonField(field reflect.StructField) (string, bool) {
	tag := field.Tag.Get("json")
	if tag == "" {
		return field.Name, false
	}
	parts := strings.Split(tag, ",")
	name := parts[0]
	if name == "" {
		name = field.Name
	}
	optional := false
	for _, part := range parts[1:] {
		if part == "omitempty" {
			optional = true
			break
		}
	}
	if field.Type.Kind() == reflect.Pointer {
		optional = true
	}
	return name, optional
}

func isIntKind(kind reflect.Kind) bool {
	return kind >= reflect.Int && kind <= reflect.Int64
}

func isFloatKind(kind reflect.Kind) bool {
	return kind == reflect.Float32 || kind == reflect.Float64
}

func ternary[T any](condition bool, whenTrue, whenFalse T) T {
	if condition {
		return whenTrue
	}
	return whenFalse
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from %s", dir)
		}
		dir = parent
	}
}
